server:
  port: 8082
#  servlet:
#    context-path: /user
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/proj2
    password: t14d2dk9
    driver-class-name: com.mysql.cj.jdbc.Driver